# Generated by Django 2.0.4 on 2018-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Episodes', models.CharField(max_length=100)),
                ('Ratings', models.CharField(max_length=100)),
                ('Members', models.CharField(max_length=100)),
            ],
        ),
    ]
