# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=10)),
                ('Episodes', models.IntegerField()),
                ('Ratings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Members', models.IntegerField()),
            ],
        ),
    ]
