# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0002_auto_20180329_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='Type',
            field=models.CharField(max_length=100),
        ),
    ]
