# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0003_auto_20180410_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='assets/data/anime.csv')),
            ],
        ),
    ]
