# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='assets/data'),
        ),
    ]
